[versions]
# The latest versions are available at https://lambdaurora.dev/tools/import_quilt.html
minecraft = "1.20.1"
quilt_mappings = "1.20.1+build.23"
quilt_loader = "0.20.2"

quilted_fabric_api = "7.2.1+0.88.0-1.20.1"

midnight_lib = "1.4.1-quilt"
modmenu_version = "7.2.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

# Required dependencies
midnight_lib = { module = "maven.modrinth:midnightlib", version.ref = "midnight_lib" }

# Optional dependencies
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu_version" }

quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version = "1.3.+" }
